replicaCount: 1

image:
  repository: dihechen/speedtest
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/issuer: "letsencrypt"
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - speed.dihe.moe
    - speedtest.dihe.moe
  tlsSecretName: speedtest-tls
